name: job-dev-sync-tss
on: workflow_dispatch
jobs:
  run-job-sync-tss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get release tag
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=docker.pkg.github.com/$GITHUB_REPOSITORY/$APPLICATION:main
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE
      - uses: nais/deploy/actions/deploy@v1
        name: run job sync-tss on dev-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .hotnais/nais-job-sync-tss.yaml
          VARS: .hotnais/dev/config.json
          VAR: commit=${{ github.sha }}