name: job-sync-tss
on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image version (sha, eg. e49c9d6637b40113ee8d86737915ae8cec49dca3)'
        required: true
        default: 'latest'
        type: string
      cluster:
        description: 'Cluster'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
jobs:
  run-job-sync-tss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get release tag
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=ghcr.io/$GITHUB_REPOSITORY/$APPLICATION:${{ inputs.imageVersion }}
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE
      - uses: nais/deploy/actions/deploy@v1
        name: run job sync-tss on ${{ inputs.cluster }}-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}-gcp
          RESOURCE: .hotnais/nais-job-sync-tss.yaml
          VARS: .hotnais/${{ inputs.cluster }}/config.json
          VAR: commit=${{ github.sha }}